// <auto-generated />
using System;
using Lab19_3_.P03_SalesDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab19_3_.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20231212191327_ProductsAddColumnDescription")]
    partial class ProductsAddColumnDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreditCardNumber = "6759977435253900",
                            Email = "Mabel0@hotmail.com",
                            Name = "Mabel Steuber"
                        },
                        new
                        {
                            Id = 2,
                            CreditCardNumber = "6011-3298-1327-5473",
                            Email = "Edna_Mante@hotmail.com",
                            Name = "Edna Mante"
                        },
                        new
                        {
                            Id = 3,
                            CreditCardNumber = "6376-9629-4830-2256",
                            Email = "Antonia_Ferry71@hotmail.com",
                            Name = "Antonia Ferry"
                        },
                        new
                        {
                            Id = 4,
                            CreditCardNumber = "6706624395792725",
                            Email = "Jerome.Roob@gmail.com",
                            Name = "Jerome Roob"
                        },
                        new
                        {
                            Id = 5,
                            CreditCardNumber = "3528-2810-9415-4708",
                            Email = "Hilda66@yahoo.com",
                            Name = "Hilda Price"
                        },
                        new
                        {
                            Id = 6,
                            CreditCardNumber = "5434-0702-3690-1565",
                            Email = "Jeanette.Conroy53@gmail.com",
                            Name = "Jeanette Conroy"
                        },
                        new
                        {
                            Id = 7,
                            CreditCardNumber = "6709662648398699",
                            Email = "Miriam.Treutel@gmail.com",
                            Name = "Miriam Treutel"
                        },
                        new
                        {
                            Id = 8,
                            CreditCardNumber = "6388-0700-5431-3327",
                            Email = "Chelsea67@hotmail.com",
                            Name = "Chelsea Runolfsson"
                        },
                        new
                        {
                            Id = 9,
                            CreditCardNumber = "3574-7545-8367-3415",
                            Email = "Lynn.Waelchi@hotmail.com",
                            Name = "Lynn Waelchi"
                        },
                        new
                        {
                            Id = 10,
                            CreditCardNumber = "6763988180751478200",
                            Email = "Victoria_Gislason4@gmail.com",
                            Name = "Victoria Gislason"
                        });
                });

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Practical Soft Sausages",
                            Price = 545.5936f,
                            Quantity = 88
                        },
                        new
                        {
                            Id = 2,
                            Name = "Practical Cotton Shirt",
                            Price = 853.9472f,
                            Quantity = 46
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intelligent Granite Computer",
                            Price = 343.28452f,
                            Quantity = 43
                        },
                        new
                        {
                            Id = 4,
                            Name = "Licensed Rubber Bacon",
                            Price = 584.2415f,
                            Quantity = 93
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fantastic Plastic Computer",
                            Price = 187.06796f,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 6,
                            Name = "Awesome Soft Pants",
                            Price = 421.91278f,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 7,
                            Name = "Practical Cotton Towels",
                            Price = 350.6449f,
                            Quantity = 57
                        },
                        new
                        {
                            Id = 8,
                            Name = "Licensed Steel Mouse",
                            Price = 745.66693f,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gorgeous Metal Chicken",
                            Price = 553.50635f,
                            Quantity = 97
                        },
                        new
                        {
                            Id = 10,
                            Name = "Awesome Granite Car",
                            Price = 253.09038f,
                            Quantity = 92
                        });
                });

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CustomerId = 10,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 5,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 6,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 3,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 2,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 10,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 8,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 10,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 8,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 2,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 5,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 7,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 5,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 4,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 1,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 1,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 2,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 2,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 1,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 5,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 2,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 2,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 1,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 6,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 6,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 1,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 9,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 8,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 1,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 8,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 8,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 9,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 3,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 6,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 1,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 10,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 8,
                            Date = new DateOnly(2023, 12, 13),
                            ProductId = 8,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 3,
                            Date = new DateOnly(2023, 12, 12),
                            ProductId = 9,
                            StoreId = 2
                        });
                });

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StoreId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toy - Borer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Schowalter and Sons"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brekke, Kilback and Harvey"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Block, Green and Gulgowski"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Funk, Hermann and Gaylord"
                        });
                });

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Sale", b =>
                {
                    b.HasOne("Lab19_3_.P03_SalesDatabase.Data.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab19_3_.P03_SalesDatabase.Data.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab19_3_.P03_SalesDatabase.Data.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Lab19_3_.P03_SalesDatabase.Data.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
